name: Update App

on:
  schedule:
    - cron: '0 4 * * 1'  # Runs every Monday at 03:00 UTC
  push:
    branches:
       - main

jobs:
    run-script:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10' # Specify your desired Python version
        - name: Install dependencies
          run: pip install -r requirements.txt # If you have a requirements.txt
        - name: Run Python script
          run: vinyl_collection_search_app.py
